### ISSUE TITLE
Customize padding, margins, line-height and general size of buttons

### ISSUE THREAD

**Issue by QuinntyneBrown** [arciisine/MaterialThemeGenerator#1]
I'm adjusting all the relevant font configuration settings, but I can not seem to reduce the actual size of buttons.

I see the font size adjusting (being reduced), but I want to get rid of all the padding and make the actual button a lot smaller.

Is this possible using the Material Theme Generator?

**Comment by arciisine** [comment]
There are a lot of individual variables that can be set in the scss generation process.  I want to be able to expose more of those in a logical manner as there are quite a bit of them.  

With respect to the button padding, is this for all buttons? Icon, text, etc.  Or specific buttons?  I could also attempt to make some of the elements padding (button, input, chips) relative to the font size as well.  Let me take a look at that and see if there is an easy solution.

**Comment by arciisine** [comment]
Buttons, and chips should now be relative to font-size, and buttons also respect line-height for height of the button.  Let me know if this is working as you expect it, and if so, I can close the issue.
