### ISSUE TITLE
Accessing color values from component scss

### ISSUE THREAD

**Issue by jkyoutsey** [arciisine/MaterialThemeGenerator#10]
This is an awesome project. We've branched it and are hosting it internally as reference for our themes/styling. Thank you.

How would I get a value from the theme?

For example, I would like to use the light/dark secondary-text value.  How, in my component scss, would I get the current theme's secondary-text color?

`color: map-get($mat-light-theme-foreground, 'secondary-text');` would work to get the light theme, and switching the variable would work for the dark theme.  But not sure how to reliably do this for both light/dark in Angular component scss.

Thanks!

**Comment by arciisine** [comment]
The theme is setup using the material theme sass helpers, and so it would be the same way as using a default material scss theme.  Additionally, I've started exposing some CSS variables for colors which allow for using the variables, even in plain CSS.

**Comment by arciisine** [comment]
Per the specific request of accessing both themes, I don't know if the material theme helpers are setup for that sort of activity.  I think the general idea is that a theme is comprehensive, and that you wouldn't access more than one theme at a time.  

Per my previous comment, all variables could be exposed appropriately, even as CSS  variables if needed.

**Comment by arciisine** [comment]
Thanks for the bug and PR, has been deployed, and is looking good.
