### ISSUE TITLE
mat-form-field letter spacing

### ISSUE THREAD

**Issue by ABergerTestAchats** [arciisine/MaterialThemeGenerator#14]
The generator adding "letter-spacing" property to the class bellow.

`.mat-form-field {
  font-size: inherit;
  font-weight: 400;
  line-height: 1.125;
  font-family: Roboto;
  letter-spacing: 1.5px; }`

This is generating an issue with the outline version of mat-form-field.

![image](https://user-images.githubusercontent.com/59646885/72716016-d2ab3400-3b71-11ea-9b8c-501495ae387c.png)

The floating label is not calculated correctly and it's also not present in the css from angular material

![image](https://user-images.githubusercontent.com/59646885/72716158-0e45fe00-3b72-11ea-84b6-018e4d1075ae.png)

Here the version without the letter-spacing.

![image](https://user-images.githubusercontent.com/59646885/72716314-45b4aa80-3b72-11ea-870e-d3297f3805ac.png)

**Comment by arciisine** [comment]
Looking at the material source code and the demo site, that 1.5 letter spacing does not seem to be coming from the customized theme, but material itself.  I could definitely be mistaken, but when I set all letter spacing to 2px, I still saw the 1.5px on the mat-label.

**Comment by arciisine** [comment]
Following up on this, I check the angular material codebase, and there is no mention of fieldset.  It looks like they do not consider or provision for this in the code base.  A PR to the angular material team to align the fieldset with the theme would probably be best.
