### ISSUE TITLE
A question, not an issue

### ISSUE THREAD

**Issue by mikejunt** [arciisine/MaterialThemeGenerator#16]
This is just a question but I am curious about a snippet of the code generated by the theme generator.   I really appreciate this tool and it was really crucial in a complex theming scheme I used in a project.   I have noticed that the generator creates 3 snippets of css for the body that all look thus:

body {
  --accent-color: #f5d130;
  --accent-lighter-color: #fcf1c1;
  --accent-darker-color: #f0c01e;
  --text-accent-color: #{$dark-primary-text};
  --text-accent-lighter-color: #{$dark-primary-text};
  --text-accent-darker-color: #{$dark-primary-text};
}

Does this actually do anything?  I've never seen anything that looks like it anywhere else and I notice that because it is not tied to the material theme, it is active all the time even if your theme is tied to a specific class.   I made a sports-based app that uses 30 themes for 30 team colors, and so I end up with 90 of these in the active css at all times, and it doesn't appear that they actually do anything.   Can I safely delete them?  Or find a way to modify them to be conditional on the theme classes (eg body.theme-class)?  Is it just informational?

Thanks again for a fantastic tool.  I could not have made the app I did without it.

**Comment by arciisine** [comment]
This is using the CSS custom property standard, which is intended for general theming for websites and components.  You can read more at: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by mikejunt** [comment]
Thanks for that; somehow I had never encountered that.

That is for extensibility and meeting standards, since AM uses map-get and their mat-color mixin to transfer color properties, correct?

**Comment by arciisine** [comment]
Sorry for not responding.  I didn't see the question.  Yeah it's meant for
extensibility and customizing at run time, outside of sass

**Comment by mikejunt** [comment]
Hey no problem, it's not really your job to teach me random things about CSS standards; I appreciate it.   I'll probably remove them from my app, or find a way to make them conditional along with the custom theme classes.   I have a sports-themed application that rotates between 30 custom themes depending on the user's favorite team and/or the team you're currently viewing data on, and so I have 90 of them in constant conflict even though the themes are properly on their own classes.
