### ISSUE TITLE
Tooltips are not shown in light themes

### ISSUE THREAD

**Issue by cre8** [arciisine/MaterialThemeGenerator#17]
According to this [issue](https://github.com/angular/components/issues/18139) they changed the behavior for the background. So tooltips will use a light background in the light version.

The `$mat-light-theme-background` has to be extended with tooltip, e.g.
```
$mat-light-theme-background: (
...
tooltip: $light-bg-darker-20,
)
```

**Comment by arciisine** [comment]
Do you know what specific version of material this is tied to?  I might need to support multiple if this is a breaking change.

**Comment by arciisine** [comment]
Actually, I think I got it figured out, should be deployed with tooltips added to the UI for the tabs, and the tooltip bg should be tied to the dark background color.
