### ISSUE TITLE
Remove need for manual SVG iconsets

### ISSUE THREAD

**Issue by EdricChan03** [arciisine/MaterialThemeGenerator#19]
As per https://github.com/google/material-design-icons/issues/773#issuecomment-467730230

**Comment by arciisine** [comment]
That's fantastic.  I'll take a look when I'm free. If you are interested,
this should also be a pretty constrained PR.

**Comment by arciisine** [comment]
Okay, so looking at it, they are missing fonts for Rounded and Two Tone.  I'll take a look at what it would it take to handle both.

**Comment by arciisine** [comment]
Okay, so it was a little more involved than I had anticipated.  The live system should be updated to use the icon fonts instead of the svg set.
