### ISSUE TITLE
Tooltip colors not generated

### ISSUE THREAD

**Issue by bobvandenberge** [arciisine/MaterialThemeGenerator#20]
In the map's for the `$mat-light-theme-background` and `$mat-dark-theme-background` there is a new property since Angular v9 called `tooltip`. This isn't generated in the scss which caused the tooltip to not have a background. 

The generator should be updated to include this property.

**Comment by arciisine** [comment]
This was a deployment issue, as the tooltips were added previously.  Should be deployed now.
