### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by b-mi** [arciisine/MaterialThemeGenerator#21]
Hello, how to use generated scss files for dynamic change themes in angular 9 application?
Would you create link in stackblitz.com?
Thank you.

**Comment by arciisine** [comment]
You just need to include the sass or css file from the generator in your project.  You can copy and paste the sass content it into styles.scss

**Comment by fernandotetu** [comment]
Hey There, 

That's awesome your tool, it's very helpful! 

I have a question about this. 
How I can choose between light and dark themes?

Following your previous tip, I got to set my custom theme, however, all the time I have the dark mode as default. 

Could you help me? 

I have a question about this. 
How I can choose between light and dark themes?

Following your tip I could set my custom theme, however all the time I have the dark mode.

**Comment by arciisine** [comment]
In the UI at the top, you can toggle the primary theme between light and
dark.  This determines the default theme.  If you add the css class
`theme-alternate` to any node in the dom, it should pick up the alternate
theme (light or dark, depending on your primary).

**Comment by b-mi** [comment]
How to change <body> background-color according to light / dark theme? Thanks

**Comment by nayfin** [comment]
add class `theme-alternate` to body of page to get alternate theme
