### ISSUE TITLE
share link embedded into generated scss

### ISSUE THREAD

**Issue by MatthewDavidTravers** [arciisine/MaterialThemeGenerator#32]
I'm not seeing a way to re-import a them back from code into the editor. Could be a good feature to have to update a theme.

Would it be possible to add the shared link into the generated code at the top of the file as shown below. With this you could re-import it back into the editor

Generated theme by Material Theme Generator
https://materialtheme.arcsine.dev
[SHARED LINK]

**Comment by arciisine** [comment]
I think adding in the shareable link into the top would be a great idea.

**Comment by arciisine** [comment]
This is now in prod, let me know if you have any issues with it.  Thanks for the idea @MatthewDavidTravers.
