### ISSUE TITLE
Background color not working - V12

### ISSUE THREAD

**Issue by krasnyuk** [arciisine/MaterialThemeGenerator#40]
Hey, I've upgraded my app to V12 with new syntax for material theme. Here is a link to my theme:
https://materialtheme.arcsine.dev/?c=YHBhbGV0dGU$YHByaW1hcnk$YF48Jv~YQiIsIj9lcjwm~~PGIiwiO2VyPCb~yCt$LCIlPmBePCb~n0QiLCI~ZXI8Jv~ixyIsIjtlcjwm~4Mtfiwid2Fybj5gXjwm~wAAIiwiP2VyPCb~s7MiLCI7ZXI8Jv8AAH4sIj9UZXh0PCYAAAAiLCI~PTwm$vr6IiwiO1RleHQ8Jv~~~yIsIjs9PCYfKU1$LCJmb250cz5bYEA8KC00fixgQDwoLTN$LGBAPCgtMn4sYEA8KC0xfixgQDxoZWFkbGluZX4sYEA8dGl0bGV$LGBAPHN1YiktMn4sYEA8c3ViKS0xfixgQDxib2R5LTJ$LGBAPGJvZHktMX4sYEA8YnV0dG9ufixgQDxjYXB0aW9ufixgQDxpbnB1dCIsInNpemU$bnVsbH1dLCJpY29uczxGaWxsZWQiLCI~bmVzcz5mYWxzZSwidmVyc2lvbj4xMn0%3D

The problem is that it uses the default background color (#212121) instead of the custom background color (#1f294d).
![image](https://user-images.githubusercontent.com/15047467/118991746-a9303180-b98c-11eb-82bc-91e1671c5cf3.png)

For components background same issue:
![image](https://user-images.githubusercontent.com/15047467/118991858-c533d300-b98c-11eb-81e8-fdef228158c3.png)

**Comment by arciisine** [comment]
Thanks for the report.  If I can't get it fixed today will probably be a
day or two.

**Comment by arciisine** [comment]
Should be fixed. The change to v12 was a little more nuanced than just the module switch over.

**Comment by krasnyuk** [comment]
Thanks, yeah, I see that now it requires to pass background config as a separate property

**Comment by samkristoff** [comment]
I also had to add the `mat-app-background` class to the `body` element to make this work.

in **index.html** I changed
```
<body class="mat-typography">
    <app-root></app-root>
</body>
```

to

```
<body class="mat-typography mat-app-background">
    <app-root></app-root>
</body>
```
