### ISSUE TITLE
Store state in url params to make created themes easily sharable 

### ISSUE THREAD

**Issue by nayfin** [arciisine/MaterialThemeGenerator#41]
Feature Request
If the theme config state was stored in url, I could share my custom theme with link or even bookmark it to save it for later.  I'm interested in contributing this feature, just let me know if you're interested.

**Comment by arciisine** [comment]
Thanks @nayfin for the feedback.  This should already be the case when you click share, and it should also be embedded in the output for easy reference/modification.  Please let me know if something is missing or not working properly.

**Comment by nayfin** [comment]
No, it's working great, I'm just blind apparently. Thanks for the great product, saved me tons of time and let me easily try a ton of different combos.
