### ISSUE TITLE
Themeing build errors

### ISSUE THREAD

**Issue by diomededavid** [arciisine/MaterialThemeGenerator#42]
This is not so much of an error as a helpful tip. Yarn will cause build errors, I was running my  build with yarn. It will complain about the `@use '~@angular/material' as mat;` being in a loop.

**Comment by nikitalpopov** [comment]
For me, these tilda and semicolon cause build errors with Angular 13:
<img width="273" alt=" 2021-11-28 at 11 35 04" src="https://user-images.githubusercontent.com/6189087/143764386-331e976c-4caa-4cca-b67e-b299ddfb7855.png">

<img width="505" alt=" 2021-11-28 at 11 34 26" src="https://user-images.githubusercontent.com/6189087/143764393-c8954081-0c36-4048-b295-da816607fb06.png">

**Comment by arciisine** [comment]
I haven't worked on Angular 13 compatibility, so there might be some changes needed there to make that work.

**Comment by arciisine** [comment]
@nikitalpopov I just deployed an update for supporting v13.  The tilde at the front has been removed in v13.
