### ISSUE TITLE
List fonts

### ISSUE THREAD

**Issue by hhsissi** [arciisine/MaterialThemeGenerator#43]
Hi, 

Great tool you built there.

Though, i had a small issue concerning mat-list-item styles. Seems like fonts are not applied to them.
All i had to do is add this small snippet to fix it:

`.mat-list-item {
  font-family: 'Lato';
}`

"Lato" is the font i'm using.
Thanks for this nice tool!

**Comment by arciisine** [comment]
Interesting. I'll need to add the list items to the sample output screen.  By deafult this should be working, but maybe something is off.

**Comment by arciisine** [comment]
So I just updated the UI to include showing list items.  The font for body-1 controls the list content styling.
